# Generated by Django 3.2.5 on 2022-12-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_holds', models.CharField(max_length=120)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.farmer')),
            ],
        ),
    ]
