# Generated by Django 3.2.5 on 2022-12-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
