# Generated by Django 3.2.5 on 2022-12-09 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_auto_20221209_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_holds', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.farmer')),
            ],
        ),
    ]
