# Generated by Django 3.2.5 on 2022-12-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerpersonaldetails',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='farmerpersonaldetails',
            name='applicant_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmerpersonaldetails',
            name='coapplicant_income',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmerpersonaldetails',
            name='credit_history',
            field=models.IntegerField(choices=[(1, '1'), (0, '0')], null=True),
        ),
        migrations.AddField(
            model_name='farmerpersonaldetails',
            name='dependent',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True),
        ),
        migrations.AddField(
            model_name='farmerpersonaldetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmerpersonaldetails',
            name='loan_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmerpersonaldetails',
            name='loan_amount_term',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmerpersonaldetails',
            name='loan_status',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmerpersonaldetails',
            name='married',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmerpersonaldetails',
            name='property_area',
            field=models.CharField(choices=[('Urban', 'Urban'), ('Semiurban', 'Semiurban'), ('Rural', 'Rural')], default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='farmerpersonaldetails',
            name='self_employed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='crop_proposed',
            field=models.IntegerField(choices=[(1, 'Commercial'), (2, 'Traditional')], default=2),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='enviromental_condition',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Poor')], default=3),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='farmer_repuation_locals',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Poor')], default=2),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='fertility_classification',
            field=models.IntegerField(choices=[(1, 'Fertile'), (2, 'Normal'), (3, 'Infertile')], default=2),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='govt_subsidy_availability',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Can be arranged'), (3, 'Not available')], default=1),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='land_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='machinery_availability',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Poor')], default=2),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='manpower_availability',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Poor')], default=2),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='market_location',
            field=models.IntegerField(choices=[(1, '< 5km'), (2, '< 10km'), (3, '< 20'), (4, '< 50'), (5, '> 50')], default=1),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='method_of_cultivation',
            field=models.IntegerField(choices=[(1, 'Organic'), (2, 'Inorganic'), (3, 'Hybrid')], default=3),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='seed_fertilizer_availability',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Poor')], default=2),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='soil_fertility',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Poor')], default=3),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='storage_system',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Poor')], default=2),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='technology_usage',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Poor')], default=2),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='topography',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Poor')], default=2),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='transport_system',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Poor')], default=2),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='water_arrangement',
            field=models.IntegerField(choices=[(1, 'Good'), (2, 'Normal'), (3, 'Poor')], default=2),
        ),
        migrations.AlterField(
            model_name='farmerpersonaldetails',
            name='education',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='landproperties',
            name='crop_marketibility',
            field=models.IntegerField(choices=[(1, 'International'), (2, 'National'), (3, 'Domestic')], default=2),
        ),
    ]
