# Generated by Django 3.2.5 on 2022-12-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20221209_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerPersonalDetails',
        ),
        migrations.DeleteModel(
            name='LandDetails',
        ),
        migrations.DeleteModel(
            name='LandProperties',
        ),
    ]
