# Generated by Django 3.2.5 on 2022-12-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_farmerpersonaldetails_landdetails_landproperties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landdetails',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='landproperties',
            name='land',
        ),
        migrations.DeleteModel(
            name='FarmerPersonalDetails',
        ),
        migrations.DeleteModel(
            name='LandDetails',
        ),
        migrations.DeleteModel(
            name='LandProperties',
        ),
    ]
