# Generated by Django 3.2.5 on 2022-12-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerPersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_no', models.IntegerField()),
                ('address', models.TextField()),
                ('area_given', models.FloatField()),
                ('area_calculated', models.FloatField()),
                ('cordinate1_x', models.FloatField()),
                ('cordinate1_y', models.FloatField()),
                ('cordinate2_x', models.FloatField()),
                ('cordinate2_y', models.FloatField()),
                ('cordinate3_x', models.FloatField()),
                ('cordinate3_y', models.FloatField()),
                ('cordinate4_x', models.FloatField()),
                ('cordinate4_y', models.FloatField()),
                ('n', models.IntegerField(default=4)),
                ('soil_image', models.ImageField(upload_to='images/landDetails/soil_images')),
                ('crop_image', models.ImageField(upload_to='images/landDetails/crop_images')),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jai_kisaan.farmerpersonaldetails')),
            ],
        ),
    ]
