# Generated by Django 3.2.5 on 2022-12-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jai_kisaan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landdetails',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='FarmerPersonalDetails',
        ),
        migrations.DeleteModel(
            name='LandDetails',
        ),
    ]
