# Generated by Django 3.2.5 on 2022-12-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jai_kisaan', '0003_farmerpersonaldetails_landdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='landdetails',
            name='crop_image',
            field=models.ImageField(null=True, upload_to='images/landDetails/crop_images'),
        ),
        migrations.AddField(
            model_name='landdetails',
            name='soil_image',
            field=models.ImageField(null=True, upload_to='images/landDetails/soil_images'),
        ),
    ]
